### ISSUE TITLE
Proper usage of requests module

### ISSUE THREAD

**Issue by NimitS1** [NimitS1/expediaRequester#1]
I made a mistake of not using the correct reference for requests module. The requester.py needs to make requests like requests.get('url', params=parameters).

**Comment by abit2** [comment]
need to add a params here as None and change all the called get with a extra parameter params, right?

**Comment by NimitS1** [comment]
No.
Currently I have added all the URL parameters within the URL string itself. That is not how one should do it actually. The better way to do it would be to pass those URL parameters as a separate parameter to the requests method (http://docs.python-requests.org/en/master/user/quickstart/)

Something like this:
parameters = {'apiKey' : self.api_key }
requests.get('http://terminal2.expedia.com:80/x/cruise/search/sailings/filters', params = parameters)

**Comment by abit2** [comment]
let me have a crack at it

**Comment by NimitS1** [comment]
Sure! :) 👍

**Comment by NimitS1** [comment]
Heads up,
you would need to handle the situation where a particular parameter passed to the wrapper would be None. In that case the corresponding URL parameter should also not be present in the URL. 
If you have a problem handling that case, let me know. I'll help you

**Comment by NimitS1** [comment]
Solved in pull request #2
